from typing import Dict, Any

LANG_HEADERS = {
    "python": "# Generated by DevForge Ultra\n",
    "ts": "// Generated by DevForge Ultra\n",
    "js": "// Generated by DevForge Ultra\n",
    "html": "<!-- Generated by DevForge Ultra -->\n",
    "css": "/* Generated by DevForge Ultra */\n",
    "pinescript": "//@version=5\n// Generated by DevForge Ultra\n",
    "xml": "<!-- Generated by DevForge Ultra -->\n",
}

def suggest_architecture(goal: str, detail: int = 2):
    return {"goal": goal, "detail": detail, "plan": ["Requirements", "Stack", "Scaffold", "Build", "Test", "Ship"]}

def generate_code(prompt: str, language: str = "python", context: Dict[str, Any] = None) -> str:
    header = LANG_HEADERS.get(language, "")
    if language == "python" and "fastapi" in prompt.lower():
        return header + """
from fastapi import FastAPI
app = FastAPI()
@app.get("/")
def home():
    return {"ok": True, "msg": "Hello from generated FastAPI app"}
"""
    if language == "html":
        return header + """
<!doctype html><html><head><meta charset="utf-8"><title>Generated</title></head>
<body><h1>Hello</h1></body></html>
"""
    if language == "pinescript":
        return header + """
indicator("ULTRA", overlay=true)
len=input.int(14); plot(ta.ema(close,len))
"""
    return header + f"# Prompt\n# {prompt}\n# TODO: Connect a provider for richer generation."
